# Generated by Django 3.1.7 on 2021-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customeremail', models.CharField(max_length=200)),
                ('Itemid', models.CharField(max_length=200)),
                ('Itemname', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('imageurl', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(max_length=10)),
            ],
        ),
    ]
