# Generated by Django 3.1.7 on 2021-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
