# Generated by Django 3.1.7 on 2022-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_auto_20211227_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderconform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customeremail', models.CharField(max_length=200)),
                ('Itemid', models.CharField(max_length=200)),
                ('Itemname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
