# Generated by Django 3.1.7 on 2022-03-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_orderconform'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconform',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
