# Generated by Django 3.1.7 on 2022-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_previousorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('securitycode', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
